#!/bin/bash

set -o errexit

wget https://dl.pstmn.io/download/latest/linux64 -O postman.tar.gz
echo "Extracting the new tar in /opt ..."
sudo tar -xzf postman.tar.gz -C /opt
echo "Removing postman.tar.gz ..."
rm postman.tar.gz
echo "Done!"
